version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:3.4.0
    container_name: kv-storage-tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
      - tarantool_data:/var/lib/tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=admin
    command: tarantool /opt/tarantool/init.lua
    healthcheck:
      test: ["CMD-SHELL", "status"]
      interval: 15s
      timeout: 2s
      retries: 10
    networks:
      - kv-storage-network

  kv-storage:
    build: .
    container_name: kv-storage-app
    ports:
      - "8080:8080"
    depends_on:
      tarantool:
        condition: service_healthy
    environment:
      - TARANTOOL_HOST=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_USERNAME=admin
      - TARANTOOL_PASSWORD=admin
    volumes:
      - ./config:/app/config
    networks:
      - kv-storage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  tarantool_data:
    driver: local

networks:
  kv-storage-network:
    driver: bridge 