version: '3.8'
services:
  tarantool:
    image: tarantool/tarantool:3.4.0
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
      - tarantool_data:/var/lib/tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=admin
    command: tarantool /opt/tarantool/init.lua

  kv-storage:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - tarantool
    environment:
      - TARANTOOL_HOST=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_USERNAME=admin
      - TARANTOOL_PASSWORD=admin
    volumes:
      - ./config:/app/config

volumes:
  tarantool_data:
