services:
  - type: web
    name: tarantool
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.tarantool
    autoDeploy: true
    envVars:
      - key: TARANTOOL_USER_NAME
        value: admin
      - key: TARANTOOL_USER_PASSWORD
        value: admin
    ports:
      - 3301

  - type: web
    name: kv-storage
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: TARANTOOL_HOST
        value: tarantool
      - key: TARANTOOL_PORT
        value: 3301
      - key: TARANTOOL_USERNAME
        value: admin
      - key: TARANTOOL_PASSWORD
        value: admin
    ports:
      - 8080
    dependsOn:
      - serviceName: tarantool
