app:
  name: "kv-storage"
  environment: "${APP_ENV:-development}"

http_server:
  port: "${HTTP_PORT:-8080}"
  read_timeout: "${HTTP_READ_TIMEOUT:-30s}"
  write_timeout: "${HTTP_WRITE_TIMEOUT:-30s}"

tarantool:
  host: "${TARANTOOL_HOST:-localhost}"
  port: ${TARANTOOL_PORT:-3301}
  username: "${TARANTOOL_USERNAME:-admin}"
  password: "${TARANTOOL_PASSWORD:-admin}"
  timeout: "${TARANTOOL_TIMEOUT:-5s}"